language: python

# use container-based infrastructure
sudo: false

python:
  - '2.6'
  - '2.7'

env:
  matrix:
    - BACKEND=hsqldb TESTNAME=test_integration.HsqldbTest
    - BACKEND=sqlitejdbc TESTNAME=test_integration.SqliteXerialTest
    - BACKEND=sqlitepy TESTNAME=test_integration.SqlitePyTest

matrix:
  # exclude:
  #   - python: 2.7
  #     env: BACKEND=sqlitejdbc
  include:
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3 BACKEND=hsqldb TESTNAME=test_integration.HsqldbTest
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7-b3 BACKEND=hsqldb TESTNAME=test_integration.HsqldbTest

before_install:
  - ci/before_install.sh
  - source $HOME/myvirtualenv/bin/activate

install:
  - pip install jip==0.7
  - pip install -e .
  - pip install -r test-requirements.txt
  - jip install org.xerial:sqlite-jdbc:3.7.2
  - jip install org.hsqldb:hsqldb:1.8.0.10
  - pip install coveralls

script:
  - export CLASSPATH=$VIRTUAL_ENV/javalib/*
  - coverage run --source jaydebeapi test/testsuite.py $TESTNAME

after_success:
  coveralls
